version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 30634
      POSTGRES_DB: expense_tracker
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5402:5432"

  web:
    image: test
    container_name: flask_web_app
    environment:
      FLASK_APP: app.py
    volumes:
      - .:/app
    ports:
      - "5004:5000"
    depends_on:
      - postgres

volumes:
  db_data:

